"""
GitHub Copilot code detection engine
"""
import re
import logging
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)


class CopilotDetector:
    """Detect Copilot-generated code using heuristics and metadata"""
    
    def __init__(self):
        self.copilot_indicators = [
            # Comment patterns typical of Copilot
            r'# Generated by.*copilot',
            r'# TODO:.*copilot',
            r'# Copilot suggestion',
            
            # Common Copilot comment styles
            r'# This function',
            r'# This class',
            
            # Metadata in git commits
            r'Co-authored-by:.*GitHub Copilot',
        ]
    
    def detect_from_content(self, content: str) -> bool:
        """Detect Copilot code from content patterns"""
        content_lower = content.lower()
        
        # Check for explicit Copilot markers
        for pattern in self.copilot_indicators:
            if re.search(pattern, content_lower, re.IGNORECASE):
                return True
        
        # Heuristic: Very generic variable names common in AI code
        generic_patterns = [
            r'\b(data|result|value|item|obj|temp)\d*\s*=',
            r'def\s+\w+\(.*\):\s*$',  # Functions with no docstrings
        ]
        
        # Check for generic patterns
        for pattern in generic_patterns:
            if re.search(pattern, content):
                return True
        
        # Additional heuristics:
        # 1. Very verbose comments that explain obvious things (common in AI code)
        comment_lines = [line for line in content.split('\n') if line.strip().startswith('#')]
        if len(comment_lines) > len(content.split('\n')) * 0.3:  # More than 30% comments
            return True
        
        # 2. Generic function names with no context
        if re.search(r'def\s+(process|handle|execute|run|main)\s*\(', content, re.IGNORECASE):
            if not re.search(r'""".*"""', content, re.DOTALL):  # No docstring
                return True
        
        # 3. Overly generic error handling
        if re.search(r'except\s+Exception\s*:', content) and not re.search(r'except\s+\w+Error\s*:', content):
            # Has generic Exception but no specific error types
            return True
        
        return False
    
    def detect_from_metadata(self, metadata: Dict[str, Any]) -> bool:
        """Detect Copilot code from commit/PR metadata"""
        # Check commit message
        commit_message = metadata.get("commit_message", "").lower()
        if "copilot" in commit_message or "ai-generated" in commit_message:
            return True
        
        # Check author
        author = metadata.get("author", "").lower()
        if "copilot" in author:
            return True
        
        # Check PR labels
        labels = metadata.get("labels", [])
        if any("copilot" in str(label).lower() for label in labels):
            return True
        
        return False
    
    def detect(self, content: str, metadata: Optional[Dict[str, Any]] = None) -> bool:
        """Main detection method combining all heuristics"""
        if metadata:
            if self.detect_from_metadata(metadata):
                return True
        
        return self.detect_from_content(content)
